GET http://localhost:8008/
# Get the command PID
###
PUT http://localhost:8008/start
# Start the command with the original 'run' command

###
###
PUT http://localhost:8008/stop
# Stop the command

###
###
POST http://localhost:8008/restart/
Content-Type: application/json

{
  "old" : "video-ft.yml",
  "new" : "/tmp/config.yml"
}

###

GET http://localhost:9999

###
# Test the example app
